
INSTAGRAM_USERNAME = "INSTAGRAM_USERNAME_HERE"
INSTAGRAM_PASSWORD = "INSTAGRAM_PASSWORD_HERE"

DISCORD_GUILD_ID = DISCORD_GUILD_ID_HERE


CHECK_INTERVAL_SECONDS = 1800

PRESENCE_TYPE = "watching"
PRESENCE_MESSAGE = "QWER"


DATABASE_PATH = "data/bot_database.db"
LOG_FILE_PATH = "logs/bot.log"


DELAY_BETWEEN_USERS = (20, 60)